# Generated by Django 5.0.6 on 2025-02-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_client_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='below_poverty_line',
            field=models.BooleanField(blank=True, help_text='Please select Yes or No', null=True, verbose_name='Does the client live below the poverty line (below $2500 per month)?'),
        ),
    ]
